server:
  port: 8888

spring:
  application:
    name: cloud-server
  profiles:
    active:
      - native
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:/config
        bootstrap: true

  main:
    allow-bean-definition-overriding: true