server:
  port: 8765

spring:
  application:
    name: gateway-server
  main:
    allow-circular-references: true
  cloud:
    config:
      fail-fast: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations.[/**].allowCredentials: true
        corsConfigurations.[/**].allowedOrigins: *
        corsConfigurations.[/**].allowedHeaders: *
        corsConfigurations.[/**].allowedMethods: HEAD,GET,POST,PUT,DELETE,OPTIONS

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]