version: '3.8'

x-kafka-server:
  &kafka-config
  environment:
    SPRING_KAFKA_BOOTSTRAP_SERVERS: http://kafka:29092

x-cloud-server:
  &cloud-config
  environment:
    SPRING_CLOUD_CONFIG_URI: http://cloud-server:8888

x-naming-server:
  &discovery-config
  environment:
    EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
    MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

x-data-server:
  &datasource-config
  environment:
    POSTGRES_USER: loga
    POSTGRES_PASSWORD: Log@2024
    POSTGRES_DB: loga

services:
  cloud-server:
    build:
      context: ./cloud-server
      dockerfile: ./Dockerfile
    image: cloud-server
    restart: always
    ports:
      - "8888:8888"
    networks:
      loga:
        ipv4_address: 172.20.0.2

  naming-server:
    build:
      context: ./naming-server
      dockerfile: ./Dockerfile
    image: naming-server
    <<: *cloud-config
    depends_on:
      - cloud-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      loga:
        ipv4_address: 172.20.0.3

  zipkin-server:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"
    networks:
      loga:
        ipv4_address: 172.20.0.4

  gateway-server:
    build:
      context: ./gateway-server
      dockerfile: ./Dockerfile
    image: gateway-server
    <<: *discovery-config
    depends_on:
      - naming-server
    ports:
      - "8765:8765"
    networks:
      loga:
        ipv4_address: 172.20.0.5

  data-server:
    image: postgres:alpine3.19
    restart: always
    <<: *datasource-config
    ports:
      - "25432:5432"
    networks:
      loga:
        ipv4_address: 172.20.0.8

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      loga:
        ipv4_address: 172.20.0.6

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:9092"
    networks:
      loga:
        ipv4_address: 172.20.0.7

  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: ./Dockerfile
    image: authentication-service
    depends_on:
      - naming-server
      - data-server
    <<: *discovery-config
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://data-server:5432/loga
      SPRING.DATASOURCE.USERNAME: loga
      SPRING.DATASOURCE.PASSWORD: Log@2024
      SPRING.JPA.HIBERNATE.DDL.AUTO: update

    ports:
      - "8001:8001"
    networks:
      loga:
        ipv4_address: 172.20.0.10

networks:
  loga:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1