version: '3.8'
services:
  cloud-server:
    build:
      context: ./cloud-server
      dockerfile: ./Dockerfile
    image: cloud-server
    restart: always
    ports:
      - "8888:8888"
    networks:
      loga:
        ipv4_address: 172.20.0.2
    container_name: cloud-server

  naming-server:
    build:
      context: ./naming-server
      dockerfile: ./Dockerfile
    image: naming-server
    environment:
      SPRING_CLOUD_CONFIG_URI: http://cloud-server:8888
    depends_on:
      - cloud-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      loga:
        ipv4_address: 172.20.0.3
    container_name: naming-server

  zipkin-server:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"
    networks:
      loga:
        ipv4_address: 172.20.0.4
    container_name: zipkin-server

  gateway-server:
    build:
      context: ./gateway-server
      dockerfile: ./Dockerfile
    image: gateway-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
    depends_on:
      - naming-server
    ports:
      - "8765:8765"
    networks:
      loga:
        ipv4_address: 172.20.0.5
    container_name: gateway-server

  data-server:
    image: postgres:alpine3.19
    restart: always
    environment:
      POSTGRES_USER: loga
      POSTGRES_PASSWORD: Log@2024
      POSTGRES_DB: loga
    ports:
      - "25432:5432"
    networks:
      loga:
        ipv4_address: 172.20.0.8
    container_name: data-server

  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: ./Dockerfile
    image: authentication-service
    depends_on:
      - naming-server
      - data-server
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://data-server:5432/loga
      SPRING.DATASOURCE.USERNAME: loga
      SPRING.DATASOURCE.PASSWORD: Log@2024
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
    ports:
      - "8001:8001"
    networks:
      loga:
        ipv4_address: 172.20.0.10
    container_name: authentication-service

networks:
  loga:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1