server:
  port: 8089

spring:
  application:
    name: authentication-service
  cloud:
    config:
      enabled: false
  devtools:
    restart:
      enabled: true
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:25432/loga
    username: loga
    password: Log@2024
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
  jackson:
    serialization:
      fail-on-empty-beans: false
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:8761/eureka

logging:
  level:
    web: DEBUG